packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@trpc/server": ^11.7.2
  better-auth: ^1.4.9
  ai: ^6.0.3
  "@trpc/client": ^11.7.2
  "@polar-sh/better-auth": ^1.1.3
