export const secrets = {
  DatabaseUrl: new sst.Secret("DatabaseUrl"),
  DatabaseUrlPooler: new sst.Secret("DatabaseUrlPooler"),
  BetterAuthSecret: new sst.Secret("BetterAuthSecret"),
  GoogleApiKey: new sst.Secret("GoogleApiKey"),
  CloudflareZoneId: new sst.Secret("CloudflareZoneId"),
  ResendApiKey: new sst.Secret("ResendApiKey"),
  PosthogKey: new sst.Secret("PosthogKey"),
  SentryDsn: new sst.Secret("SentryDsn"),
  SentryAuthToken: new sst.Secret("SentryAuthToken"),
  SentryOrg: new sst.Secret("SentryOrg"),
  SentryProject: new sst.Secret("SentryProject"),
  PodscanApiToken: new sst.Secret("PodscanApiToken"),
  AdminEmail: new sst.Secret("AdminEmail"),
};
