ALTER TABLE "podcast" ADD COLUMN "guid" text;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "description" text;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "image_url" text;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "publisher_name" text;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "rss_url" text;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "language" text;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "region" text;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "itunes_id" text;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "spotify_id" text;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "is_duplicate_of" text;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "last_posted_at" timestamp;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "last_scanned_at" timestamp;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "podscan_created_at" timestamp;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "podscan_updated_at" timestamp;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "episode_count" integer;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "reach_score" integer;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "is_active" boolean;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "is_duplicate" boolean;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "has_guests" boolean;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "has_sponsors" boolean;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "categories" jsonb;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "iab_categories" jsonb;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "reach" jsonb;--> statement-breakpoint
ALTER TABLE "podcast" ADD COLUMN "brand_safety" jsonb;